[project]
name = "eharmony"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Justin Goodwin", email = "jgoodwin314@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "scipy>=1.17.1",
    "torch>=2.10.0",
    "torch-harmonics>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]

[dependency-groups]
dev = [
    "cartopy>=0.25.0",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "matplotlib>=3.10.8",
    "ruff>=0.15.5",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint.isort]
known-first-party = ["eharmony", "tests"]

[tool.ruff.lint]
# Enable all common rules (E, F, I) as a baseline
select = ["E", "F", "I"]
# Ignore specific rules across the entire project
ignore = [
    "E501",  # Disable line too long checks (if you use a formatter like Black)
    "D100",  # Disable missing public module documentation
    "D101",  # Disable missing public class documentation
    "E722",  # Disable bare `except`
    "E731",  # Disable lambda to def
    "E741",  # Disable ambiguous variable name
]
